name: Create and publish Docker images

on:
  push:
    branches: ["main", "release"]
    paths: ["VERSION"]
    tags: ["v*.*.*"]
  workflow_run:
    workflows: ["Node.js CI", "CodeQL Advanced"]
    types: [completed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------------------
      # log_output module
      # ---------------------------
      - name: Extract metadata for log_output
        id: meta-log
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/log_output
          tags: main

      - name: Build & push log_output image
        id: build-log
        uses: docker/build-push-action@v4
        with:
          context: ./log_output
          push: true
          tags: ${{ steps.meta-log.outputs.tags }}
          labels: ${{ steps.meta-log.outputs.labels }}
          outputs: type=digest

      - name: Attest log_output image
        uses: actions/attest@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/log_output
          subject-digest: ${{ steps.build-log.outputs.digest }}
          predicate-type: https://slsa.dev/provenance/v1
          push-to-registry: true
          show-summary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---------------------------
      # todo-app module
      # ---------------------------
      - name: Extract metadata for todo-app
        id: meta-todo
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/todo-app
          tags: main

      - name: Build & push todo-app image
        id: build-todo
        uses: docker/build-push-action@v4
        with:
          context: ./the_project/todo-app
          push: true
          tags: ${{ steps.meta-todo.outputs.tags }}
          labels: ${{ steps.meta-todo.outputs.labels }}
          outputs: type=digest

      - name: Attest todo-app image
        uses: actions/attest@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/todo-app
          subject-digest: ${{ steps.build-todo.outputs.digest }}
          predicate-type: https://slsa.dev/provenance/v1
          push-to-registry: true
          show-summary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
